language: java
sudo: required
jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
script:
  - ./mvnw clean install -B

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master